my_new/my_new_web/my_newproject/my_newproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_newprojectapp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_new/my_new_web/my_newproject/my_newprojectapp/urls.py
from . import views
from django.urls import path


app_name = 'my_newprojectapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

my_new/my_new_web/my_newproject/my_newprojectapp/models.py
from django.db import models

class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

my_new/my_new_web/my_newproject/my_newprojectapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

my_new/my_new_web/my_newproject/my_newprojectapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movie
from . forms import MovieForm


def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, "index.html", context)

def detail(request, movie_id):
    movie = Movie.objects.get(id = movie_id)
    return render(request, "details.html", {'movie': movie})

def add_movie(request):
    if request.method == "POST":
            name = request.POST.get('name')
            desc = request.POST.get('desc')
            year = request.POST.get('year')
            img = request.FILES['img']
            movie = Movie(name=name, desc=desc,year=year, img=img)
            movie.save()
    return render(request,"add.html")

def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form':form, 'movie':movie})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

my_new/my_new_web/my_newproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post", enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text", name="name", placeholder="Enter the name of movie"><br>
    <input type="text", name="desc", placeholder="Enter Description"><br>
    <input type="number", name="year", placeholder="Enter the Year of the movie"><br>
    <input type="file", name="img"><br>
    <input type="submit"><br>

</form>
  {% endblock %}

my_new/my_new_web/my_newproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'  %}">

</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        ONLINE MOVIE STORE
    </a>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

my_new/my_new_web/my_newproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    Are you sure want to delete this?
    <input class="btn btn-warning" type="submit" value="Submit">

</form>
{% endblock %}

my_new/my_new_web/my_newproject/templates/details.html
{% extends 'base.html' %}
{% block body %}

<div class="card"style="width: 18rem;" >
  <img class="card-img-top" src="{{movie.img.url}}" height="200" width="200">
  <div class="card-body">
      <h5 class="card-title">{{movie.name}}</h5>
        <p class="card-text">{{movie.desc}}</p>
      <a href="{% url 'my_newprojectapp:update' movie.id %}" class="btn btn-primary">Update</a>
      <a href="{% url 'my_newprojectapp:delete' movie.id %}" class="btn btn-primary">Delete</a>

  </div>
</div>
{% endblock %}

my_new/my_new_web/my_newproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST", enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit">



</form>
{% endblock %}

my_new/my_new_web/my_newproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
         {% for i in movie_list %}
        <div class="col-md-3">
          <div class="card" >
            <img class="card-img-top" src="{{i.img.url}}" height="300"  >
                 <div class="card-body">
                 <h5 class="card-title">{{i.name}}</h5>
                 <p class="card-text">{{i.desc}}</p>
                <a href="{% url 'my_newprojectapp:detail' i.id %}" class="btn btn-primary">Details</a>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>






    {% endblock %}